class AppImages {
  AppImages._();
  static const String iconBasePath = "assets/icons/";
  static const String guest = "${iconBasePath}guest.png";
  static const String visitingHelp = "${iconBasePath}visiting_help.png";
  static const String delivary = "${iconBasePath}delivery.png";
  static const String cab = "${iconBasePath}cab.png";
  static const String complaint = "${iconBasePath}complaint.png";
  static const String gateKeeper = "${iconBasePath}gatekeeper.png";

  static const String preapprovedVisitor =
      "${iconBasePath}pre-approved-vistors.png";
  static const String communityMember = "${iconBasePath}comunity_member.png";
  static const String disscussionForum = "${iconBasePath}disscussion_forum.png";
  static const String societyEvents = "${iconBasePath}society_events.png";
  static const String noticeBoard = "${iconBasePath}notice_board.png";
  static const String marketPlace = "${iconBasePath}market_place.png";
  static const String emergencyNo = "${iconBasePath}emergency_no.png";
  static const String panicButton = "${iconBasePath}panic_button.png";
  static const String complaintHistory = "${iconBasePath}complaint_history.png";
  static const String visitorHistory = "${iconBasePath}visiting_help.png";
  static const String guestHistory = "${iconBasePath}guest_history.png";
  static const String familyMember = "${iconBasePath}family_member.png";
  static const String bills = "${iconBasePath}bills.png";
  static const String call = "${iconBasePath}call.png";
  static const String voted = "${iconBasePath}voted.png";
  static const String demoUser = "${iconBasePath}demouser.png";
  static const String call2 = "${iconBasePath}call2.png";
  static const String cnic = "${iconBasePath}cnic.png";
  static const String gateNo = "${iconBasePath}gateNo.png";
  static const String complaints = "${iconBasePath}complaints.png";
  static const String person = "${iconBasePath}person.png";
  static const String timer = "${iconBasePath}timer.png";
  static const String message = "${iconBasePath}message.png";
  static const String splash = "${iconBasePath}spalsh.png";
  static const String date = "${iconBasePath}date.png";
  static const String support = "${iconBasePath}support.png";
  static const String disscussion_forum = "${iconBasePath}disscussion.png";
  static const String notice = "${iconBasePath}notice.png";
  static const String date2 = "${iconBasePath}date2.png";
  static const String addfamilymember = "${iconBasePath}add_family_member.png";
  static const String house = "${iconBasePath}house.png";
  static const String logo = "${iconBasePath}logo.png";
  static const String buy = "${iconBasePath}buy.png";
  static const String sell = "${iconBasePath}sell.png";
  static const String fire = "${iconBasePath}fire.png";
  static const String medicalIssue = "${iconBasePath}medicale_issue.png";
  static const String robbery = "${iconBasePath}thief.png";
  static const String shortCircuit = "${iconBasePath}shortcircuit.png";
  static const String other = "${iconBasePath}other.png";
  static const String house2 = "${iconBasePath}house2.png";
  static const String adminComplaint = "${iconBasePath}admin_comlaint.png";
  static const String homeblue = "${iconBasePath}homeblue.png";
  static const String complaintsblue = "${iconBasePath}complaint_blue.png";
  static const String noticeboardblue = "${iconBasePath}noticeboard_blue.png";
  static const String disscussionblue = "${iconBasePath}disscussion_blue.png";
  static const String homegrey = "${iconBasePath}homegrey.png";
  static const String complaintsgrey = "${iconBasePath}complaint_grey.png";
  static const String noticeboardgrey = "${iconBasePath}noticeboard_grey.png";
  static const String disscussiongrey = "${iconBasePath}disscussion_grey.png";
  static const String logoutUser = "${iconBasePath}logou_usert.png";
  static const String updateProfile = "${iconBasePath}update_profile.png";
  static const String updatePhone = "${iconBasePath}update_phone.png";
  static const String voting = "${iconBasePath}voting.png";
  static const String question = "${iconBasePath}question.png";
  static const String rules = "${iconBasePath}rules.png";
  static const String country = "${iconBasePath}country.png";
  static const String block = "${iconBasePath}block-user.png";
  static const String parkingSlots = "${iconBasePath}parking_slots.png";

  ///  SVG
  static const String smartgate = "${iconBasePath}smartgate.svg";
  static const String spalshDivider = "${iconBasePath}splashdivider.svg";
  static const String splashLine = "${iconBasePath}splashlines.svg";
  static const String splashSvg = "${iconBasePath}splashsvg.svg";
  static const String splashSvg2 = "${iconBasePath}splashsvg2.svg";
  static const String splashSvg3 = "${iconBasePath}splashsvg3.svg";
}
